# Generated by Django 2.0.6 on 2019-02-21 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pageNumber', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=100)),
                ('publishDate', models.DateField(default=datetime.datetime(2019, 2, 21, 17, 19, 49, 461584, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.DateField(default=datetime.datetime(2019, 2, 21, 17, 19, 49, 461945, tzinfo=utc))),
            ],
        ),
    ]
