# Generated by Django 2.0.6 on 2019-02-21 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookCar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(default=datetime.datetime(2019, 2, 21, 17, 48, 2, 993936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
